[package]
name = "transy-platform"
version = "0.1.0"
edition = "2024"

[package.metadata.deb]
name = "transy"
maintainer = "tgiap.dev"
extended-description = "Minimal on-demand pop-up translator for Linux and macOS"
section = "翻译"
priority = "optional"

[dependencies]
transy-core = { path = "../transy-core" }
egui = "0.31"
eframe = { version = "0.31", default-features = false, features = ["default_fonts", "glow", "x11", "wayland"] }
tokio = { version = "1", features = ["full"] }
tray-icon = "0.24"
global-hotkey = "0.8"
image = { version = "0.25", default-features = false, features = ["png"] }
